---

collections:
  - name: https://github.com/ansible-collections/community.general.git
    type: git
    version: master
    
roles:
  - src: https://github.com/superlumic/ansible-role-homebrew.git
    name: roderik.superlumic-homebrew
    version: master

  - src: https://github.com/superlumic/ansible-role-osx-defaults.git
    name: roderik.superlumic-osx-defaults
    version: master

  - src: https://github.com/superlumic/ansible-role-computername.git
    name: roderik.superlumic-computername
    version: master

  - src: https://github.com/superlumic/ansible-role-cli.git
    name: roderik.superlumic-cli
    version: master

  - src: https://github.com/superlumic/ansible-role-mysql.git
    name: roderik.superlumic-mysql
    version: master

  - src: https://github.com/superlumic/ansible-role-php.git
    name: roderik.superlumic-php
    version: master

  - src: https://github.com/superlumic/ansible-role-sublimetext.git
    name: roderik.superlumic-sublimetext
    version: master

  - src: https://github.com/superlumic/ansible-role-node.git
    name: roderik.superlumic-node
    version: master

  - src: https://github.com/superlumic/ansible-role-postgresql.git
    name: roderik.superlumic-postgresql
    version: master

  - src: https://github.com/superlumic/ansible-role-vim.git
    name: roderik.superlumic-vim
    version: master

  - src: https://github.com/superlumic/ansible-role-modjk.git
    name: roderik.superlumic-modjk
    version: master

  - src: https://github.com/superlumic/ansible-role-skylab.git
    name: roderik.superlumic-skylab
    version: master
